name: debug mac arm

on:
  push:
    branches:
      - apple_silicon

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
    - name: build deps & slicer
      run: ./BuildMacOS.sh -ia

